#!/bin/sh

# Copyright (C) 2014-2015 Brian Downing.  MIT License.

set -e

if [ -z "$1" ]; then
    echo Usage: $0 file.c '<cc args...>' >&2
    exit 1
fi

llvm=/usr
for d in /usr/lib/llvm-3.5 /usr/lib/llvm-3.4 /usr /usr/local; do
    if [ -e "$d"/include/clang-c/Index.h -a -e "$d"/lib/libclang.so ]; then
        llvm="$d"
    fi
done

orig_dir="$(pwd)"
script_dir="$(dirname "$0")"
file="$1"; shift

pp_output="/tmp/lj-cdefdb-preprocessed$$.c"
trap "rm -f $pp_output" 0
${CLANG:-clang} -E -dD "$@" "$file" > "$pp_output"

cd "$script_dir/ljclang"
make inc="$llvm"/include libdir="$llvm"/lib libljclang_support.so
LD_LIBRARY_PATH=.:"$llvm"/lib:${LD_LIBRARY_PATH:-.} luajit ../process.lua "$pp_output" > "$orig_dir/cdefdb.c"
cd "$orig_dir"

${CC:-cc} -fPIC -shared -o cdefdb.so cdefdb.c
echo "cdefdb.so generated"
