#!/bin/sh

# Copyright (C) 2014-2015 Brian Downing.  MIT License.

set -e

lj_cdefdb_dir=${LJ_CDEFDB_DIR:-$(luajit -e "print(require('cdefdb.config').dir)")}

if [ -z "$1" ]; then
    echo Usage: $0 '(file.c|-)' '<output dir>' '<cc args...>' >&2
    exit 1
fi

file="$1"; shift
. "$lj_cdefdb_path"/functions.sh
out=$(readlink -f "$1"); shift

pp_tmpdir="/tmp/lj-cdefdb-$$"
mkdir -p "$pp_tmpdir"
trap "rm -rf $pp_tmpdir" 0
pp_output="$pp_tmpdir/preprocessed$$.c"
${CC:-cc} -E -dD "$@" "$file" > "$pp_output"

hash=$(sha1sum "$pp_output" | cut -b1-8)

mkdir -p "$out"
run_in_ljclang ../gen-cdefdb.lua "$pp_output" "$out" "$hash"

mkdir -p "$out"/cdefdb.d
mv "$out"/"$hash".db "$out"/cdefdb.d
if [ -e "$out"/"$hash".c ]; then
    mkdir -p "$out"/stubs
    ${CC:-cc} -fPIC -shared -O2 -o "$out"/stubs/"$hash".so "$out"/"$hash".c
    rm "$out"/"$hash".c
fi
